import type { concepts } from "@/lib/db/schema";

type ConceptSeed = typeof concepts.$inferInsert;

/** Flashcards. `front` is the prompt, `back` is the answer (markdown allowed). */
export const CONCEPTS: ConceptSeed[] = [
  // ── Fundamentals: operating model ──
  {
    id: "c-three-levers",
    topicId: "returns-levers",
    front: "The three levers of LBO returns.",
    back: "**EBITDA growth, multiple expansion, debt paydown.** Ops teams primarily drive the first (and de-risk the third). Multiple expansion is the least controllable and least defensible to underwrite.",
    difficulty: 1,
    tags: ["returns", "levers"],
  },
  {
    id: "c-100-day-plan",
    topicId: "fundamentals-value-plan",
    front: "What is a 100-day plan?",
    back: "The prioritized value-creation roadmap executed in the first ~100 days post-close: **quick wins, governance/KPIs stood up, and the big-ticket initiatives scoped and resourced.** Sets the cadence for the hold.",
    difficulty: 1,
    tags: ["value-creation", "100-day"],
  },
  {
    id: "c-ebitda-bridge",
    topicId: "fundamentals-value-plan",
    front: "EBITDA bridge components.",
    back: "**Volume, price/mix, cost inflation, productivity/cost-out, one-offs/run-rate adjustments.** A bridge explains the walk from entry EBITDA to a later period — the basis for underwriting growth.",
    difficulty: 2,
    tags: ["ebitda", "bridge"],
  },
  {
    id: "c-centralized-vs-embedded",
    topicId: "fundamentals-operating-model",
    front: "Centralized vs embedded ops model.",
    back: "**Centralized** = one pooled team serving all PortCos (Capstone, Blackstone PortOps). **Embedded** = operators sit inside sector deal teams (Carlyle, TPG). Hybrid models exist; some firms also lean on an external advisor bench.",
    difficulty: 2,
    tags: ["operating-model"],
  },
  {
    id: "c-why-ops-matters",
    topicId: "fundamentals-operating-model",
    front: "Why does operational value creation matter more now than in the 1980s?",
    back: "Cheap leverage and multiple expansion did the heavy lifting in earlier eras. Today entry multiples are high and rates are higher, so **operational EBITDA growth is the most reliable, underwrite-able source of return** — roughly half of value creation in recent deals.",
    difficulty: 2,
    tags: ["operating-model", "history"],
  },
  {
    id: "c-operating-partner",
    topicId: "fundamentals-operating-model",
    front: "What does an operating partner / portfolio-ops professional actually do?",
    back: "Diagnoses value-creation opportunities, builds the value-creation plan with management, and **drives execution without line authority** — installing KPIs, leading initiatives (pricing, cost, commercial), and reporting progress to the deal team and board.",
    difficulty: 2,
    tags: ["operating-model", "role"],
  },
  {
    id: "c-value-creation-plan",
    topicId: "fundamentals-value-plan",
    front: "What is a value-creation plan (VCP)?",
    back: "The thesis-linked, quantified roadmap of initiatives for the hold period — each with an owner, an EBITDA/cash target, milestones, and a tracked run-rate. The 100-day plan is its front end.",
    difficulty: 2,
    tags: ["value-creation"],
  },
  // ── Returns math ──
  {
    id: "c-moic-def",
    topicId: "returns-lbo-math",
    front: "Definition of MOIC.",
    back: "**Multiple on Invested Capital** = exit equity value ÷ entry equity invested. A gross cash-on-cash multiple; ignores time. 2.5–3.0x over ~5 years is a common target.",
    difficulty: 1,
    tags: ["moic"],
  },
  {
    id: "c-irr-vs-moic",
    topicId: "returns-lbo-math",
    front: "IRR vs MOIC — what's the difference?",
    back: "**MOIC** is total cash multiple (time-blind). **IRR** is the annualized, time-weighted return. A 2.0x in 3 years (~26% IRR) beats a 2.5x in 7 years (~14% IRR). Faster exits and early distributions lift IRR without changing MOIC much.",
    difficulty: 2,
    tags: ["irr", "moic"],
  },
  {
    id: "c-rule-of-72",
    topicId: "returns-lbo-math",
    front: "Rule of 72 — and how to use it in a paper LBO.",
    back: "Years to double ≈ 72 ÷ IRR%. Inverting: a **2.0x over 5 years ≈ 72/5 ≈ ~15% IRR**; a 3.0x over 5 years ≈ ~25%. Use it to sanity-check IRR from MOIC and hold period without a calculator.",
    difficulty: 2,
    tags: ["irr", "rule-of-72"],
  },
  {
    id: "c-moic-irr-anchors",
    topicId: "returns-lbo-math",
    front: "5-year IRR anchors for round MOICs.",
    back: "Over a 5-year hold: **2.0x ≈ 15%, 2.5x ≈ 20%, 3.0x ≈ 25%, 4.0x ≈ 32%.** Memorize these — they let you state an IRR instantly in a paper LBO.",
    difficulty: 3,
    tags: ["irr", "moic", "anchors"],
  },
  {
    id: "c-sources-uses",
    topicId: "returns-lbo-math",
    front: "What goes in a Sources & Uses?",
    back: "**Uses:** purchase enterprise value, refinanced debt, transaction/financing fees. **Sources:** new debt tranches, sponsor equity (the plug), management rollover, sometimes a seller note. Sources must equal uses.",
    difficulty: 2,
    tags: ["sources-uses", "lbo"],
  },
  {
    id: "c-entry-equity",
    topicId: "returns-lbo-math",
    front: "How do you get entry equity in a simple LBO?",
    back: "Entry equity = entry EV − net debt raised (after fees). If you buy at 10x $100M EBITDA = $1,000M EV financed 60% debt, equity ≈ $400M (plus fees). Equity is the denominator of MOIC.",
    difficulty: 2,
    tags: ["lbo", "equity"],
  },
  {
    id: "c-exit-equity",
    topicId: "returns-lbo-math",
    front: "How do you build exit equity value?",
    back: "**Exit EV = exit EBITDA × exit multiple.** Then **exit equity = exit EV − net debt at exit.** Debt paydown over the hold (FCF sweep) shrinks net debt, transferring enterprise value to equity.",
    difficulty: 2,
    tags: ["lbo", "exit"],
  },
  {
    id: "c-leverage-effect",
    topicId: "returns-levers",
    front: "Why does leverage amplify equity returns?",
    back: "Debt is a fixed claim; all EV growth above the debt accrues to equity. With more debt, a given % EV increase is a larger % equity increase — and debt paydown converts EV to equity. It cuts both ways: leverage magnifies losses too.",
    difficulty: 2,
    tags: ["leverage"],
  },
  {
    id: "c-flat-multiple-return",
    topicId: "returns-levers",
    front: "In a flat-multiple deal, what creates the return?",
    back: "**EBITDA growth and debt paydown** — multiple expansion contributes nothing when you exit at the entry multiple. This is the disciplined way to underwrite: don't rely on selling at a higher multiple than you paid.",
    difficulty: 2,
    tags: ["levers", "multiple"],
  },
  {
    id: "c-return-attribution",
    topicId: "returns-levers",
    front: "What is return attribution / a value-creation bridge?",
    back: "Decomposing total equity gain into **EBITDA growth, multiple change, and debt paydown (+ FCF)**. Lets you show how much return came from operations vs financial engineering vs market re-rating — the credibility test for an ops thesis.",
    difficulty: 3,
    tags: ["attribution"],
  },
  // ── Diagnostics: levers ──
  {
    id: "c-pricing-lever",
    topicId: "diagnostics-levers",
    front: "Why is pricing usually the highest-ROI early lever?",
    back: "A price increase drops almost entirely to EBITDA (little incremental cost) and is fast to implement. Most lower-mid-market PortCos have **fragmented, undisciplined pricing** — list/pocket-price gaps, no escalation clauses, discount leakage.",
    difficulty: 2,
    tags: ["pricing", "levers"],
  },
  {
    id: "c-working-capital",
    topicId: "diagnostics-levers",
    front: "Working-capital optimization — the three levers.",
    back: "**DSO** (collect receivables faster), **DPO** (extend payables), **DIO** (reduce inventory). Cutting the cash conversion cycle frees cash to pay down debt — a balance-sheet lever that lifts equity without touching EBITDA.",
    difficulty: 2,
    tags: ["working-capital"],
  },
  {
    id: "c-cost-takeout",
    topicId: "diagnostics-levers",
    front: "Cost takeout vs procurement — what's the distinction?",
    back: "**Cost takeout** = internal structural cost (headcount, footprint, SG&A, productivity). **Procurement** = third-party spend (renegotiate suppliers, consolidate vendors, spec/demand management). Procurement is often faster and less disruptive.",
    difficulty: 2,
    tags: ["cost", "procurement"],
  },
  {
    id: "c-commercial-excellence",
    topicId: "diagnostics-levers",
    front: "What is 'commercial excellence' as a value-creation lever?",
    back: "Improving the revenue engine: salesforce effectiveness (coverage, comp, CRM discipline), pricing/discount governance, cross-sell/up-sell, churn reduction, and channel mix. Growth-oriented, slower-burning than cost levers.",
    difficulty: 2,
    tags: ["commercial", "sales"],
  },
  {
    id: "c-buy-and-build",
    topicId: "diagnostics-levers",
    front: "What is a buy-and-build (add-on) strategy?",
    back: "Acquiring smaller targets onto a platform to gain scale, multiple arbitrage (buy small at low multiples, exit the larger entity at a higher one), and synergies. Ops teams drive **integration** — the part that most often disappoints.",
    difficulty: 2,
    tags: ["m&a", "add-ons"],
  },
  // ── Diagnostics: frameworks ──
  {
    id: "c-diagnose-before-act",
    topicId: "diagnostics-frameworks",
    front: "The cardinal rule of an operational case.",
    back: "**Diagnose before you act.** Decompose and benchmark the problem against peers before recommending a move. Jumping to 'cut 10% of headcount' or 'raise prices' before isolating the gap is the classic trap.",
    difficulty: 1,
    tags: ["frameworks", "diagnosis"],
  },
  {
    id: "c-margin-gap-framework",
    topicId: "diagnostics-frameworks",
    front: "How do you attack a margin gap vs peers?",
    back: "Decompose the P&L line by line vs benchmark: **gross margin (price, mix, input cost, productivity) then SG&A (sales, G&A, overhead).** Locate where the bps live, size each, then prioritize by ROI and feasibility.",
    difficulty: 3,
    tags: ["frameworks", "margin"],
  },
  {
    id: "c-prioritization",
    topicId: "diagnostics-frameworks",
    front: "How do you prioritize value-creation levers?",
    back: "Score by **impact (EBITDA/cash $) × speed-to-value × feasibility/risk × management capacity.** Sequence quick, high-confidence wins first to fund credibility, then the bigger structural plays. Don't boil the ocean.",
    difficulty: 2,
    tags: ["frameworks", "prioritization"],
  },
  {
    id: "c-quick-wins",
    topicId: "diagnostics-frameworks",
    front: "Why lead with quick wins?",
    back: "They build management's trust in the ops team, generate cash to self-fund larger initiatives, and prove the diagnosis. Credibility earned early is the currency you spend on harder change later.",
    difficulty: 2,
    tags: ["frameworks", "change"],
  },
  // ── Technicals concepts ──
  {
    id: "c-leading-lagging",
    topicId: "technicals-scenarios",
    front: "Leading vs lagging indicators — why care?",
    back: "**Lagging** indicators (revenue, EBITDA, win rate) confirm results after the fact. **Leading** indicators (pipeline coverage, ramp time, activity) predict them and let you course-correct. A good KPI set pairs both.",
    difficulty: 2,
    tags: ["metrics", "kpis"],
  },
  {
    id: "c-influence-no-authority",
    topicId: "behavioral-core",
    front: "Influence without authority — the core moves.",
    back: "**Co-own the diagnosis** (use their data), **quantify the prize**, **pilot small** to de-risk, **tie to their incentives**, and use governance (the board/KPIs) as a gentle forcing function. You lead through credibility, not command.",
    difficulty: 2,
    tags: ["behavioral", "influence"],
  },
  {
    id: "c-star",
    topicId: "behavioral-core",
    front: "STAR structure for behavioral answers.",
    back: "**Situation, Task, Action, Result.** Keep S/T tight (~20%), spend the time on *your* specific Actions, and close with a **quantified Result**. For ops roles, weave in resistance handled and influence used.",
    difficulty: 1,
    tags: ["behavioral", "star"],
  },
  {
    id: "c-why-ops-not-deal",
    topicId: "behavioral-core",
    front: "Why PE operations and not a deal-side seat?",
    back: "You want to **build value inside companies, not just price and structure them.** Consulting taught you to diagnose and drive change with management; ops is where that skill compounds, with real ownership of outcomes over a hold.",
    difficulty: 2,
    tags: ["behavioral", "commitment"],
  },
];
